{% set version = '0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bookdown
  version: {{ version|replace("-", "_") }}

source:
  fn: bookdown_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bookdown_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bookdown/bookdown_{{ version }}.tar.gz
  sha256: ec6b3502a2b15c582edfe0c8ebca917106e82d83e6e52b1d1af4ef2988a5bddf

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmltools >=0.3.6
    - r-knitr >=1.16
    - r-rmarkdown >=1.5
    - r-xfun
    - r-yaml >=2.1.14

  run:
    - r-base
    - r-htmltools >=0.3.6
    - r-knitr >=1.16
    - r-rmarkdown >=1.5
    - r-xfun
    - r-yaml >=2.1.14

test:
  commands:
    - $R -e "library('bookdown')"  # [not win]
    - "\"%R%\" -e \"library('bookdown')\""  # [win]

about:
  home: https://github.com/rstudio/bookdown
  license: GPL-3
  summary: Output formats and utilities for authoring books and technical documents with R Markdown.
  license_family: GPL3n
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]n
  license_file: '{{ environ["PREFIX"] }}\R[[:space:]]hare\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - bsennblad
