# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wZ55H65pEP6mN1nMsqZQ5fAkZssQtljyJULCCfHLjzfNSlwP2RIOsVO+HWi/Sm6KNje3NYlxf9RRPwyT8VrNhaMmzmF9JjNX6DcyIbLIYfwwXDurNQPenuJlBP0HTWb1GRFs/fSYRixw9ap3O0of6jferB7FtHPTpA4asCtLrtdleA9kJUmQ8LwIF1paPXLL6QNG7qIVX+fderGDuv52JUQcZALBxVag4QSWAUY9PShLoU2KkfoaMl6FpdFBK/imCqmFFuVI3NR2sGQs55uHz90pUxlFrHqMjuFrbcVSJ9etTm4/X/o3kD9DkA3QhhhuBzQFWgLdrfPrLa1v6ONY0ElfG6cQnzvzuCg5MFBdd/X/XfqOR+48YOw1LZfWBwF8mcbNmCope3dP+cYTMlI7yPhx6GyCcYgMifqbuOE4t66FWYJO+dE4YVM1xSqD8IHik/TKteSNf7/mRhy1PjUiazPR/bDIdc05VIzSWgSBarQW6sUPL+ubXSTcQYnCTeJNermjmDtF0U3OKo7RrcKCDw6bgtepbH1mXwjWSeiXjGIPAN93EpaK4IAikv98Y7UhumykYpN0Lv7Xis+OqB7nn+xg2fe+LwcFncli8q2lReNd+wiqfryUU28yQv/w8taxZH+0zMvPtzio+A17FA6i6TRelnNOd01TW3z3Ycx0R08="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
