travis:
  secure:
    BINSTAR_TOKEN: R77e2a8nIR5DVBB4twllFwdRwIvg7sergIDvEKB7HWlXMYHOSxRAvRkQ10vdnW5NA3mcPyHQgfrxVCC3JTnNNZYRPlWyKsf/ku662thfV9V7nwCEi5zQ61wiE+kmrYo6tVHFHkrNcJm9SJ0lwVHbQlWOC80RJ89Bjekswon8fb1IbMDeSua30bAxVfjPD8fHS1TGaepHNjJxaIevDt+aOGQYtSLiWZtMHWVdbKMe0UWMOaG5aslU+mJbWoa1d23DKoxTxzE/B7T9vOqFsWl4ezw9v3udGe+US8Dif0r3HqbTnFzizEO2hxUfyVez97iP75me+R+mGirQ2t4PCAx4IqWhEwI1uQjlNVYOXVRRHqxy3IcKqgWAsHq6Oni/YqLolBIucFCxTBLdUubS3KLvaG3/rnkxz77tRxHmlUU+gqGb7n+q88XFe4sEobk1p4v0jHx7r/z5BPKR7N8RdRcZBEN6abMlDWV/0xbZAwxjrITSzNbYMu48705LQjHmrPXViCzWgoxE8U7F7FDUhhRrW0e02nW5zgUyHkH2Ymf0zQarN/xpU3zKgOwRyNGAhfOzF2wXNUGeba+xXfA/HIuA+7BYbqB4QmrbTDgqfx6Bg6FFPD+2Tn3C3njGwsZTgjcD2AQwjI3O4YvZYgx8w5rU1iqm36uPoFYGvTumMho6094=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
