appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: wZ55H65pEP6mN1nMsqZQ5fAkZssQtljyJULCCfHLjzfNSlwP2RIOsVO+HWi/Sm6KNje3NYlxf9RRPwyT8VrNhaMmzmF9JjNX6DcyIbLIYfwwXDurNQPenuJlBP0HTWb1GRFs/fSYRixw9ap3O0of6jferB7FtHPTpA4asCtLrtdleA9kJUmQ8LwIF1paPXLL6QNG7qIVX+fderGDuv52JUQcZALBxVag4QSWAUY9PShLoU2KkfoaMl6FpdFBK/imCqmFFuVI3NR2sGQs55uHz90pUxlFrHqMjuFrbcVSJ9etTm4/X/o3kD9DkA3QhhhuBzQFWgLdrfPrLa1v6ONY0ElfG6cQnzvzuCg5MFBdd/X/XfqOR+48YOw1LZfWBwF8mcbNmCope3dP+cYTMlI7yPhx6GyCcYgMifqbuOE4t66FWYJO+dE4YVM1xSqD8IHik/TKteSNf7/mRhy1PjUiazPR/bDIdc05VIzSWgSBarQW6sUPL+ubXSTcQYnCTeJNermjmDtF0U3OKo7RrcKCDw6bgtepbH1mXwjWSeiXjGIPAN93EpaK4IAikv98Y7UhumykYpN0Lv7Xis+OqB7nn+xg2fe+LwcFncli8q2lReNd+wiqfryUU28yQv/w8taxZH+0zMvPtzio+A17FA6i6TRelnNOd01TW3z3Ycx0R08=}
